export namespace FUNCTIONS {
  export enum EMAIL_TEMPLATE {
    OFFBOARDING_APPROVER_VIEW = 'approver-view',
    OFFBOARDING_MEETING_VIEW = 'meeting-view',
    OFFBOARDING_CLOSING_PACKAGE_VIEW = 'closing-package-view',
    OFFBOARDING_SETTING_VIEW = 'setting-view',
    EXPENSO_SETTING_VIEW = 'setting-view',
    CLOSED_RECORD_VIEW = 'closed-record-view',
    TICKET_VIEW = 'ticket-view',
    TICKET_SUMMARY = 'ticket-summary',
    TICKET_REPLACE = 'ticket-replace',
    SUPPORT_TEAM_COPY = 'support-team-copy',
    ADMIN_RESET_PASSWORD_VIEW = 'reset-password-view',
    ADMIN_VERIFY_CODE_VIEW = 'verify-code-view',
    ADMIN_CREATE_COMPANY = 'company-view',
    CHECK_CODE_VIEW = 'check-code-view',
    CREATE_ADMIN_VIEW = 'create-admin-view',
    TENANT_EXPERT_VIEW = 'tenant-expert-view',
    CONTACT_US_VIEW = 'contact-us-view',
    WELCOME_CUSTOMER_VIEW = 'welcome-customer-view',
    ACCEPT_GOAL_EMPLOYEE = 'accept-goal-employee',
    ACCEPT_GOAL_MANAGER = 'accept-goal-manager',
    ADD_EMPLOYEE_TO_EMPLOYEE = 'add-employee-to-employee',
    ADD_EMPLOYEE = 'add-employee',
    ADJUST_EMPLOYEE = 'adjust-employee',
    ADJUST_MANAGER = 'adjust-manager',
    APPROVE_EVALUATION = 'approve-evaluation',
    ASSIGN_EPAS_EMPLOYEE = 'assign-epas-employee',
    EVALUATING_MANAGER = 'evaluating-manager',
    EVALUATING_EMPLOYEE = 'evaluating-employee',
    EVALUATION_EMPLOYEE = 'evaluation-employee',
    FEEDBACK = 'feedback',
    REJECT_GOAL_EMPLOYEE = 'reject-goal-employee',
    REJECT_GOAL_MANAGER = 'reject-goal-manager',
    REMOVE_EMPLOYEE_TO_EMPLOYEE = 'remove-employee-to-employee',
    REMOVE_EMPLOYEE = 'remove-employee',
    STATUS_ACTIVATED_EMPLOYEE_TEMPLATE = 'status_activated_employee_template',
    STATUS_ACTIVATED_MANAGER_TEMPLATE = 'status_activated_manager_template',
    STATUS_ACTIVATED_HR_TEMPLATE = 'status_activated_hr_template',
    STATUS_CLOSED = 'status_closed',
    STATUS_DEACTIVATED = 'status_deactivated',
    TIMESHEET_RESUBMITTED = 'timesheet-resubmitted',
    BE_NEW_ACCOUNT = 'be-new-account',
    CUSTOMER_ACCOUNT = 'customer-account',
  }

  export enum SERVICE {
    AUTH = 'auth-api',
    EXPENSO = 'expenso-api',
    BACKEND = 'api',
    TIMESHEET = 'timesheet',
    OFFBOARDING = 'offboarding-api',
    TICKET = 'ticket-api',
    EPAS = 'epas-api',
    ASSET = 'asset-api',
    CUSTOMER = 'api-customer',
    PROJECT = 'api-project',
    PAYROLL = 'payroll-api',
  }
}

export enum MODULE {
  EXPENSO = "EXPENSO",
  TIMEOFF = "TIMEOFF",
  TIMESHEET = "TIMESHEET",
  ONBOARDING = "ONBOARDING",
  OFFBOARDING = "OFFBOARDING",
  TICKET = "TICKET",
  EPAS = "EPAS",
  ASSET = "ASSET",
  AUTH = "AUTH",
  BACKEND = "BACKEND",
  CUSTOMER = "CUSTOMER"
}


